version: "3.7"

services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "127.0.0.1:${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    volumes:
      - type: bind
        source: ./wordpress
        target: "/var/www/html"

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: ./db
        target: "/var/lib/mysql"

volumes:
  wordpress:
  db:
